Repository SCons/scons, pull requests merged in 2021-11, with the labels that each got.

#4051 Remove -prerelease for MSVC 2022
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/MSCommon/vc.py
Labels: MSVC

#4056 Skip two scons-time tests on Windows
  test/scons-time/run/config/python.py
  test/scons-time/run/option/python.py
Labels: testsuite

#4057 Switch Windows CI builds to VS2022 and Py3.10
  .appveyor.yml
Labels: CI / buildbot

#4055 Some adjustments to runtest.py
  runtest.py
Labels: testsuite

#4049 Update Java support for more versions
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/JavaCommon.py
  SCons/Tool/JavaCommonTests.py
  SCons/Tool/javac.py
  SCons/Tool/javac.xml
  SCons/Tool/javah.py
  SCons/Tool/javah.xml
  doc/user/java.xml
Labels: Java

#4052 Deprecate qt tool and rearrange docs
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/qt.py
  SCons/Tool/qt.xml
  SCons/Warnings.py
  doc/man/scons.xml
  test/QT/CPPPATH-appended.py
  test/QT/CPPPATH.py
  test/QT/QTFLAGS.py
  test/QT/Tool.py
  test/QT/copied-env.py
  test/QT/empty-env.py
  test/QT/generated-ui.py
  test/QT/installed.py
  test/QT/manual.py
  test/QT/moc-from-cpp.py
  test/QT/moc-from-header.py
  test/QT/qt_warnings.py
  test/QT/reentrant.py
  test/QT/source-from-ui.py
  test/QT/up-to-date.py
Labels: Tools

#4047 Fix tests to work with FIPS enabled
  .gitignore
  CHANGES.txt
  SCons/Environment.py
  SCons/EnvironmentTests.py
  SCons/Node/NodeTests.py
  SCons/SConsign.py
  SCons/SConsignTests.py
  SCons/Scanner/Dir.py
  SCons/Scanner/DirTests.py
  SCons/Util.py
  SCons/UtilTests.py
  doc/man/scons.xml
  test/Configure/ConfigureDryRunError.py
  test/Configure/VariantDir-SConscript.py
  test/Configure/implicit-cache.py
  test/Configure/option--config.py
  test/Removed/SourceSignatures/Old/no-csigs.py
  test/Repository/variants.py
  test/SConsignFile/default.py
  test/SConsignFile/explicit-dbm-module.py
  test/SConsignFile/explicit-file.py
  test/SConsignFile/make-directory.py
  test/SConsignFile/use-dbhash.py
  test/SConsignFile/use-dbm.py
  test/SConsignFile/use-dumbdbm.py
  test/SConsignFile/use-gdbm.py
  test/implicit/changed-node.py
  test/option/hash-format.py
  test/option/option-n.py
  test/question/Configure.py
  test/sconsign/corrupt.py
  test/sconsign/nonwritable.py
  test/sconsign/script/Configure.py
  test/sconsign/script/SConsignFile.py
  test/sconsign/script/Signatures.py
  test/sconsign/script/dblite.py
  test/sconsign/script/no-SConsignFile.py
  testing/framework/TestSCons.py
Labels: FIPS

#4064 Update manpage mentions of for_signature
  doc/man/scons.xml
Labels: Documentation

#4062 Doc tweaks: make Sphinx happier [ci skip]
  SCons/Conftest.py
  SCons/Variables/__init__.py
Labels: Documentation

#4059 Restore doc of passing a dict as Scanner function
  doc/man/scons.xml
Labels: Documentation

#4063 Verify that a user-specified script via MSVC_USE_SCRIPT exists
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/MSCommon/vc.py
  test/MSVC/MSVC_USE_SCRIPT.py
Labels: MSVC

#4067 Fix tests to not hang on Windows with bad .py assoc
  CHANGES.txt
  RELEASE.txt
  SCons/Platform/win32.py
  SCons/Script/Main.py
  doc/man/scons.xml
  runtest.py
  test/scons-time/run/config/python.py
  test/scons-time/run/option/python.py
  test/sconsign/script/SConsignFile.py
  test/sconsign/script/Signatures.py
  test/sconsign/script/no-SConsignFile.py
  testing/framework/TestCmd.py
  testing/framework/TestSCons.py
  testing/framework/TestSConsMSVS.py
Labels: testsuite

#4068 Followon test fix for PR #4067
  test/scons-time/run/config/python.py
  test/scons-time/run/option/python.py
Labels: testsuite
