Repository SCons/scons, pull requests merged in 2021-01, with the labels that each got.

#3850 Create github workflow for scons build/doc
  .github/workflows/scons-package.yml
Labels: CI / buildbot

#3852 Fix awkward consvar code from ancient Python
  CHANGES.txt
  SCons/Environment.py
Labels: maintenance

#3857 Update manpage section of Fortran suffixes
  SCons/Tool/f03.xml
  SCons/Tool/f08.xml
  SCons/Tool/f77.xml
  SCons/Tool/f90.xml
  SCons/Tool/f95.xml
  SCons/Tool/fortran.xml
  doc/man/scons.xml
Labels: Subcomponent: documentation

#3849 Adjust CompilationDatase documentation
  SCons/Tool/compilation_db.xml
  doc/generated/examples/external_cdb_ex1_1.xml
  doc/generated/examples/external_cdb_ex2_1.xml
  doc/user/external.xml
Labels: Subcomponent: documentation

#3847 Switch travis-ci 3.9 to released + 20.04
  .travis.yml
  .travis/install.sh
  CHANGES.txt
  RELEASE.txt
  SCons/Platform/posix.py
  doc/user/environments.xml
  test/D/HSTeoh/Common/singleStringCannotBeMultipleOptions.py
Labels: CI / buildbot

#3844 Build up manpage information on sconscript files.
  doc/man/scons.xml
Labels: Subcomponent: documentation

#3863 UGuide: fix two erroneous uses of Append
  doc/man/scons.xml
  doc/user/environments.xml
  doc/user/sconf.xml
Labels: Subcomponent: documentation

#3870 Some small doc fiddles
  SCons/Environment.xml
  doc/generated/variables.gen
  doc/man/scons.xml
  doc/sphinx/conf.py
  doc/user/environments.xml
Labels: Subcomponent: documentation

#3874 Initial support in tests for Python 3.10
  .travis.yml
  CHANGES.txt
  SCons/Action.py
  SCons/ActionTests.py
  SCons/SubstTests.py
  SCons/Tool/docbook/__init__.py
  SCons/Variables/__init__.py
  test/Interactive/configure.py
Labels: Python 3.10

#3875 Add logic to force rebuild of lxml and cython from git versions for python 3.10
  .travis.yml
  .travis/install.sh
Labels: Python 3.10
