Repository SCons/scons, pull requests merged in 2021-04, with the labels that each got.

#3917 Make target selection a subsection in manpage
  SCons/Script/SConscript.xml
  doc/man/scons.xml
Labels: Documentation

#3920 Add some more entity links in docs
  SCons/Defaults.xml
  SCons/Tool/compilation_db.xml
  SCons/Tool/default.xml
  SCons/Tool/docbook/docbook.xml
  SCons/Tool/dvi.xml
  SCons/Tool/gas.xml
  SCons/Tool/gettext.xml
  SCons/Tool/gs.xml
  SCons/Tool/hpcc.xml
  SCons/Tool/intelc.xml
  SCons/Tool/link.xml
  SCons/Tool/packaging/packaging.xml
  doc/man/scons.xml
  doc/scons.mod
Labels: Documentation

#3894 Support custom cachedir classes
  CHANGES.txt
  RELEASE.txt
  SCons/CacheDir.py
  SCons/Environment.py
  SCons/Environment.xml
  SCons/EnvironmentTests.py
  SCons/Node/FS.py
  doc/user/caching.xml
  test/CacheDir/CACHEDIR_CLASS.py
  test/CacheDir/CACHEDIR_CLASS_fixture/SConstruct
  test/CacheDir/CACHEDIR_CLASS_fixture/file.in
  test/CacheDir/CustomCacheDir.py
  test/CacheDir/DoubleCachedirClass.py
  test/CacheDir/InvalidCustomCacheDir.py
  test/CacheDir/custom_cachedir_fixture/SConstruct
  test/CacheDir/custom_cachedir_fixture/file.in
  test/CacheDir/double_cachedir_fixture/SConstruct
  test/CacheDir/double_cachedir_fixture/file.in
  test/CacheDir/invalid_custom_cachedir_fixture/SConstruct
  test/CacheDir/invalid_custom_cachedir_fixture/file.in
  testing/framework/TestCommon.py
Labels: cachedir

#3926 Expansion of CPPDEFINES now substs consvars
  CHANGES.txt
  SCons/Defaults.py
  test/CPPDEFINES/basic.py
Labels: subst

#3928 Test harness add a from_fw to skip calls
  bin/scons-test.py
  bin/scons-time.py
  testing/framework/TestCmd.py
  testing/framework/TestCmdTests.py
  testing/framework/TestCommon.py
  testing/framework/TestCommonTests.py
  testing/framework/TestRuntest.py
  testing/framework/TestSCons.py
  testing/framework/TestSConsMSVS.py
  testing/framework/TestSCons_time.py
  testing/framework/TestSConsign.py
Labels: testsuite

#3930 Test tweaks to help testing on mingw-only win32 systems
  SCons/EnvironmentTests.py
  SCons/Tool/link.py
  test/Decider/MD5-winonly-fixture/test_parse.y
  test/LEX/LEXFLAGS.py
  test/LEX/live_mingw.py
  test/Libs/SharedLibrary-update-deps.py
  test/Libs/SharedLibrary.py
  test/MinGW/MinGWSharedLibrary.py
  test/MinGW/RCCOM.py
  test/MinGW/RCCOMSTR.py
  test/MinGW/WINDOWS_INSERT_DEF.py
  test/MinGW/bug_2799/SConstruct
  test/MinGW/mingw_uses_comstr_issue_2799.py
  test/Win32/mingw.py
  test/Win32/msvc_mingw_env.py
  test/long-lines/signature.py
  test/rebuild-generated.py
  test/scons-time/func/chdir.py
  test/scons-time/func/funcglob.py
  test/scons-time/func/tail.py
  test/sconsign/script/SConsignFile.py
  test/sconsign/script/Signatures.py
  test/sconsign/script/no-SConsignFile.py
  testing/framework/TestCommon.py
Labels: testsuite

#3723 Eliminate unnecessary calculation of the msvc installed list when finding installed visual studios
  CHANGES.txt
  SCons/Tool/MSCommon/vs.py
Labels: MSVC

#3934 Avoid exception if tool set to empty
  CHANGES.txt
  SCons/Environment.py
  SCons/EnvironmentTests.py
  SCons/Util.py
Labels: maintenance
