Repository SCons/scons, pull requests merged in 2021-07, with the labels that each got.

#3967 Bug install scons copytree recursion
  CHANGES.txt
  SCons/Tool/install.py
  test/Install/rec-sub-dir.py
Labels: Tools

#3966 Update manpage for ParseConfig [skip appveyor]
  SCons/Environment.xml
Labels: Documentation

#3965 Addopt tests
  runtest.py
  test/AddOption/.exclude_tests
  test/AddOption/args-and-targets.py
  test/AddOption/multi-arg.py
Labels: testsuite

#3969 Moved CacheDir permissions update code behind atomic rename operation.
  CHANGES.txt
  RELEASE.txt
  SCons/CacheDir.py
Labels: cachedir

#3959 Change warnings behavior of missing SConscript
  CHANGES.txt
  RELEASE.txt
  SCons/Script/SConscript.py
  test/SConscript/must_exist.py
  test/SConscript/must_exist_deprecation.py
  test/option/option-f.py
  test/option/warn-missing-sconscript.py
Labels: maintenance

#3973 Tweak doc of experimental option
  SCons/Script/SConsOptions.py
  doc/man/scons.xml
Labels: Documentation

#3975 Minor manapage tweaks
  doc/man/scons.xml
Labels: Documentation

#3980 make multi target and intermediate SConf files marked is_conftest
  CHANGES.txt
  RELEASE.txt
  SCons/Builder.py
  SCons/SConf.py
  SCons/SConfTests.py
  test/Configure/is_conftest/fixture/SConstruct
  test/Configure/is_conftest/fixture/sconstest.skip
  test/Configure/is_conftest/is_conftest.py
Labels: Ninja

#3981 fixed ninja tool is_conftest check and allow setting disable ninja execute from env
  CHANGES.txt
  SCons/Script/SConsOptions.py
  SCons/Tool/ninja/Utils.py
  SCons/Tool/ninja/__init__.py
  SCons/Tool/ninja/ninja.xml
  test/ninja/ninja_conftest.py
  test/ninja/ninja_test_sconscripts/ninja_conftest
Labels: Ninja
