Repository SCons/scons, pull requests merged in 2022-03, with the labels that each got.

#4105 Tweaks to ninja docs
  SCons/Tool/ninja/ninja.xml
  doc/user/external.xml
Labels: Documentation, Ninja

#4099 Updates to User Guide: 6/Dependencies
  RELEASE.txt
  doc/scons.mod
  doc/user/depends.xml
Labels: Documentation

#4109 Fixed URLS and python versions for setup.cfg
  CHANGES.txt
  RELEASE.txt
  setup.cfg
Labels: Release

#4107 Updates to User Guide: 22/Caching
  SCons/Environment.xml
  doc/man/scons.xml
  doc/user/caching.xml
Labels: Documentation

#4091 Man: mention $$ as subst escape
  doc/man/scons.xml
Labels: Documentation, subst

#4104 Added ninja mingw support and improved CommandGeneratorAction support
  .github/workflows/experimental_tests.yml
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/cc.xml
  SCons/Tool/clang.py
  SCons/Tool/clang.xml
  SCons/Tool/clangxx.py
  SCons/Tool/gcc.py
  SCons/Tool/gcc.xml
  SCons/Tool/gxx.py
  SCons/Tool/msvc.py
  SCons/Tool/msvc.xml
  SCons/Tool/ninja/Methods.py
  SCons/Tool/ninja/__init__.py
  SCons/Tool/ninja/ninja.xml
  SCons/Util.py
  test/ninja/mingw_command_generator_action.py
  test/ninja/ninja_test_sconscripts/sconstruct_mingw_command_generator_action
Labels: mingw, Ninja

#4115 man: rearrange the variable substitution section
  SCons/Environment.xml
  doc/man/scons.xml
Labels: Documentation, subst

#4119 Guide: update Writing Builders chapter
  doc/scons.mod
  doc/user/builders-writing.xml
Labels: Documentation

#4123 Documentation: minor fix in source xml files
  SCons/Tool/msvc.xml
  SCons/Tool/ninja/ninja.xml
Labels: Documentation

#4116 Use super call instead of direct class call
  CHANGES.txt
  SCons/Action.py
  SCons/Builder.py
  SCons/Environment.py
  SCons/EnvironmentTests.py
  SCons/Errors.py
  SCons/Job.py
  SCons/JobTests.py
  SCons/Memoize.py
  SCons/Node/Alias.py
  SCons/Node/FS.py
  SCons/Node/FSTests.py
  SCons/Node/NodeTests.py
  SCons/Node/Python.py
  SCons/SConf.py
  SCons/SConsign.py
  SCons/Subst.py
  SCons/SubstTests.py
  SCons/Tool/GettextCommon.py
  SCons/Tool/MSCommon/sdk.py
  SCons/Tool/msvs.py
  SCons/UtilTests.py
  SCons/cppTests.py
  bin/SConsDoc.py
  src/test_setup.py
  testing/framework/TestCommon.py
  testing/framework/TestRuntest.py
  testing/framework/TestSCons.py
  testing/framework/TestSCons_time.py
  testing/framework/TestSConsign.py
  testing/framework/TestUnit/taprunner.py
Labels: maintenance

#4039 Ninja: Add interactive SCons deamon for ninja to dynamically make build callbacks to
  CHANGES.txt
  RELEASE.txt
  SCons/Script/Interactive.py
  SCons/Script/Main.py
  SCons/Tool/ninja/NinjaState.py
  SCons/Tool/ninja/Utils.py
  SCons/Tool/ninja/__init__.py
  SCons/Tool/ninja/ninja.xml
  SCons/Tool/ninja/ninja_daemon_build.py
  SCons/Tool/ninja/ninja_run_daemon.py
  SCons/Tool/ninja/ninja_scons_daemon.py
  test/ninja/force_scons_callback.py
  test/ninja/iterative_speedup.py
  test/ninja/ninja_handle_control_c_rebuild.py
  test/ninja/ninja_test_sconscripts/sconstruct_control_c_ninja
  test/ninja/ninja_test_sconscripts/sconstruct_force_scons_callback
Labels: Ninja

#4126 Fix some more tests to use context-mgr open
  test/Actions/append.py
  test/Actions/function.py
  test/Actions/pre-post.py
  test/option/option--.py
  test/option/option--Q.py
  test/option/option-i.py
  test/option/option-k.py
  test/option/option-s.py
Labels: testsuite

#4124 Add a bit more info to tool "generate" function doc
  doc/man/scons.xml
Labels: Documentation
