Repository SCons/scons, pull requests merged in 2022-10, with the labels that each got.

#4246 Adjust Sphinx doc build for moved Taskmaster
  doc/sphinx/SCons.Taskmaster.rst
  doc/sphinx/SCons.rst
  doc/sphinx/index.rst
Labels: Documentation

#4244 Java scanner don't split JAVACLASSPATH on space
  CHANGES.txt
  RELEASE.txt
  SCons/Scanner/Java.py
  SCons/Scanner/JavaTests.py
  SCons/Tool/jar.xml
  SCons/Tool/javac.xml
  SCons/Tool/javah.xml
  SCons/Tool/rmic.xml
  doc/sphinx/SCons.Scanner.rst
  doc/user/java.xml
Labels: Java, scanner

#4247 Minor doc update for Value nodes
  SCons/Environment.py
  SCons/Environment.xml
  SCons/Node/Python.py
  SCons/Node/__init__.py
Labels: Documentation

#4249 [WIP] Migrate Taskmaster tracing to use python logging
  CHANGES.txt
  RELEASE.txt
  SCons/Script/Main.py
  SCons/Taskmaster/TaskmasterTests.py
  SCons/Taskmaster/__init__.py
  SCons/Util.py
Labels: taskmaster

#4250 Small cleanup in BoolVariable
  CHANGES.txt
  SCons/Variables/BoolVariable.py
  SCons/Variables/BoolVariableTests.py
  doc/man/scons.xml
  doc/user/command-line.xml
  test/Configure/issue-3469/fixture/SConstruct
  test/Copy-Option.py
  test/Parallel/multiple-parents.py
  test/Variables/BoolVariable.py
  test/Variables/help.py
  test/no-global-dependencies.py
Labels: Documentation, testsuite
