Repository SCons/scons, pull requests merged in 2022-06, with the labels that each got.

#4165 Fix missing newline when calling skip_test()
  testing/framework/TestCommon.py
Labels: maintenance, testsuite

#4166 Update ActionTests for Python 3.11
  SCons/ActionTests.py
Labels: maintenance, testsuite

#4172 doc: FORTRANCOM doesn't include cpp vars
  SCons/Tool/fortran.xml
Labels: Documentation

#4171 [NINJA] Added command line variable to pass ninja args through scons.
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/ninja/__init__.py
  SCons/Tool/ninja/ninja.xml
  SCons/Tool/packaging/__init__.py
  test/ninja/generate_and_build.py
  testing/framework/TestCmd.py
  testing/framework/TestCmdTests.py
Labels: Ninja

#4176 Test Framework tests: Windows fixes
  testing/framework/TestCmdTests.py
  testing/framework/TestCommonTests.py
Labels: testsuite

#4175 find_program_path() can now add discovered path
  CHANGES.txt
  SCons/Tool/ToolTests.py
  SCons/Tool/__init__.py
Labels: Tools

#4170 [NINJA] Added new alias 'shutdown-ninja-scons-daemon' to allow ninja to shutdown the daemon
  .github/workflows/experimental_tests.yml
  .github/workflows/runtest.yml
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/ninja/NinjaState.py
  SCons/Tool/ninja/__init__.py
  SCons/Tool/ninja/ninja_daemon_build.py
  SCons/Tool/ninja/ninja_scons_daemon.py
  requirements.txt
  test/ninja/shutdown_scons_daemon.py
  testing/framework/TestCmd.py
Labels: Ninja

#4179 Doc: mention Fortran "dialects"
  doc/generated/builders.gen
  doc/generated/functions.gen
  doc/generated/tools.gen
  doc/generated/variables.gen
  doc/generated/variables.mod
  doc/man/scons.xml
Labels: Documentation, Fortran

#4180 Fortran variants now include FORTRANCOMMONFLAGS
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/FortranCommon.py
  SCons/Tool/f03.xml
  SCons/Tool/f08.xml
  SCons/Tool/f77.xml
  SCons/Tool/f90.xml
  SCons/Tool/f95.xml
  SCons/Tool/fortran.xml
  SCons/Tool/g77.py
  SCons/Tool/g77.xml
  SCons/Tool/gfortran.py
  SCons/Tool/gfortran.xml
  SCons/Tool/ifl.py
  SCons/Tool/ifort.py
  test/Fortran/F77PATH.py
  test/Fortran/F90PATH.py
  test/Fortran/FORTRANCOMMONFLAGS.py
  test/Fortran/FORTRANFILESUFFIXES2.py
  test/Fortran/FORTRANPATH.py
  test/Fortran/fixture/myfortran.py
  test/Fortran/fixture/myfortran_flags.py
Labels: Tools, Fortran

#4168 Updated lex emitter to respect escaped spaces when climbing out of the SConscript dir
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/lex.py
  test/LEX/lex_headerfile.py
  test/LEX/lex_headerfile/spaced path/SConstruct
  test/LEX/lex_headerfile/spaced path/src/SConscript
  test/LEX/lex_headerfile/spaced path/src/lexer.l
  test/LEX/lex_headerfile/spaced path/src/lexer2.l
Labels: Tools

#4181 Doc wordsmithing - actions
  SCons/Action.xml
  SCons/Environment.xml
  doc/man/scons.xml
Labels: Documentation

#4167 doc: tweaked Builder intro section in manpage
  doc/man/scons.xml
Labels: Documentation
