Repository SCons/scons, pull requests merged in 2022-01, with the labels that each got.

#4080 Clean up lint complaints in MSCommon
  CHANGES.txt
  SCons/Tool/MSCommon/__init__.py
  SCons/Tool/MSCommon/arch.py
  SCons/Tool/MSCommon/common.py
  SCons/Tool/MSCommon/netframework.py
  SCons/Tool/MSCommon/sdk.py
  SCons/Tool/MSCommon/vc.py
  SCons/Tool/MSCommon/vs.py
Labels: maintenance

#4086 Update ActionTests.py to work for python 3.10.1+
  CHANGES.txt
  RELEASE.txt
  SCons/ActionTests.py
Labels: testsuite

#4084 Update manpage bits about env['ENV']
  SCons/Environment.py
  SCons/Environment.xml
  SCons/EnvironmentTests.py
  SCons/Tool/tex.py
  SCons/UtilTests.py
  doc/sphinx/conf.py
  requirements.txt
Labels: Documentation

#4083 Update manpage "Extending SCons" section. [skip appveyor]
  doc/man/scons.xml
  doc/scons.mod
Labels: Documentation

#4081 Add some info to User Guide on #/paths
  doc/generated/examples/hierarchy_hash_1.xml
  doc/user/hierarchy.xml
  doc/user/separate.xml
Labels: Documentation

#4087 Massage test fixtures a bit
  test/AS/fixture/myas.py
  test/AS/fixture/myas_args.py
  test/CC/CC-fixture/.exclude_tests
  test/CC/CC-fixture/mycc.py
  test/CC/CC-fixture/test1.c
  test/CC/CC-fixture/test2.C
  test/CC/CC.py
  test/CFILESUFFIX.py
  test/CPPFLAGS.py
  test/CXX/CXX-fixture/.exclude_tests
  test/CXX/CXX-fixture/myc++.py
  test/CXX/CXX.py
  test/CXX/CXXFILESUFFIX.py
  test/LEX/LEX.py
  test/LEX/LEXFLAGS.py
  test/fixture/mycompile.py
  test/fixture/mygcc.py
  test/fixture/mylex.py
  test/fixture/mylink.py
  test/fixture/mylink_win32.py
  test/fixture/myrewrite.py
  test/fixture/wrapper.py
  test/fixture/wrapper_with_args.py
Labels: testsuite

#4089 A little java/jar cleanup
  SCons/Tool/jar.py
  test/Java/JAR.py
  test/Java/JAVAC.py
  test/Java/Java-fixture/.exclude_tests
  test/Java/Java-fixture/myjar.py
  test/Java/Java-fixture/myjavac.py
  test/Java/jar_not_in_PATH.py
  test/Java/rmic_not_in_PATH.py
Labels: Java, testsuite
