Repository SCons/scons, pull requests merged in 2022-04, with the labels that each got.

#4128 Fix a ref-before-assign issue in tex tool
  CHANGES.txt
  SCons/Tool/tex.py
Labels: maintenance

#4135 Mingw tool fix to use the same search paths the generate and exists methods
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/mingw.py
Labels: Op Sys: Windows, mingw

#4139 Uguide: fix a typo of environment
  doc/user/environments.xml
Labels: Documentation
