Repository SCons/scons, pull requests merged in 2022-12, with the labels that each got.

#4085 Added error message when failure to delete partial cache retrieval occurs
  CHANGES.txt
  RELEASE.txt
  SCons/Taskmaster/TaskmasterTests.py
  SCons/Taskmaster/__init__.py
  SCons/Warnings.py
Labels: cachedir

#4253 Change --taskmaster trace logging to use Python's logging module. Added logging to NewParalllel Job class
  CHANGES.txt
  RELEASE.txt
  SCons/Taskmaster/Job.py
  SCons/Taskmaster/JobTests.py
  SCons/Taskmaster/__init__.py
Labels: taskmaster

#4277 Manpage tweaking
  SCons/Script/Main.xml
  doc/man/scons.xml
Labels: Documentation

#4279 uguide: variant dir tweaking
  RELEASE.txt
  doc/man/scons.xml
  doc/user/hierarchy.xml
  doc/user/separate.xml
  doc/user/variants.xml
Labels: Documentation, variantdir

#4281 Turn Util module into a package
  .flake8
  CHANGES.txt
  RELEASE.txt
  SCons/Util/__init__.py
  SCons/Util/envs.py
  SCons/Util/hashes.py
  SCons/Util/types.py
  SCons/UtilTests.py
Labels: maintenance
