Repository SCons/scons, pull requests merged in 2022-08, with the labels that each got.

#4205 Test framework improvements
  testing/framework/TestCmd.py
  testing/framework/TestCmdTests.py
  testing/framework/TestCommonTests.py
Labels: testsuite

#4208 Let test framework still run if no psutil
  testing/framework/TestCmd.py
Labels: testsuite

#4210 Split requirements files
  .appveyor/install.bat
  .github/workflows/scons-package.yml
  .travis.yml
  CONTRIBUTING.rst
  RELEASE.txt
  pyproject.toml
  requirements-dev.txt
  requirements-pkg.txt
  requirements.txt
  template/RELEASE.txt
Labels: maintenance, Release

#4212 [framework] use subprocess timeouts
  testing/framework/TestCmd.py
  testing/framework/TestCmdTests.py
  testing/framework/TestCommon.py
  testing/framework/TestSCons.py
Labels: testsuite

#4214 [framework] quiet Python about start() tests
  testing/framework/TestCmdTests.py
Labels: testsuite

#4217 Add ValidateOption() API
  CHANGES.txt
  RELEASE.txt
  SCons/Script/Main.py
  SCons/Script/Main.xml
  SCons/Script/SConsOptions.py
  SCons/Script/SConscript.py
  SCons/Script/__init__.py
  SCons/__init__.py
  bin/update_doc_files.sh
  doc/generated/examples/caching_ex-random_1.xml
  doc/generated/examples/troubleshoot_explain1_3.xml
  doc/generated/functions.gen
  doc/generated/functions.mod
  test/ValidateOptions.py
  test/fixture/SConstruct-check-valid-options
Labels: args_and_options

#4218 Fix excessive path escaping in runtest py
  CHANGES.txt
  runtest.py
  test/runtest/python.py
  testing/framework/TestRuntest.py
Labels: testsuite
