Repository SCons/scons, pull requests merged in 2022-11, with the labels that each got.

#4260 Update setup/installation chapter in User Guide
  CHANGES.txt
  RELEASE.txt
  doc/user/build-install.xml
Labels: Documentation

#4256 Maintenance: fix some fiddly checker errors
  SCons/Tool/docbook/docbook-xsl-1.76.1/extensions/docbook.py
  testing/framework/TestCommonTests.py
Labels: testsuite

#4255 Ninja: Fix execution environment sanitation.
  CHANGES.txt
  RELEASE.txt
  SCons/Action.py
  SCons/Platform/darwin.py
  SCons/Tool/ninja/Utils.py
  SCons/Tool/ninja/__init__.py
  SCons/Util.py
  test/ninja/shell_command.py
Labels: Ninja

#4265 Speed up a few tests for CI
  test/Actions/actions.py
  test/Alias/Alias.py
  test/Alias/Depends.py
  test/Alias/action.py
  test/CPPPATH/CPPPATH.py
  test/CacheDir/option--cs.py
  test/Default.py
  test/Fortran/F77PATH.py
  test/Fortran/F90PATH.py
  test/Fortran/FORTRANPATH.py
  test/Libs/LIBPATH.py
  test/Libs/LIBS.py
  test/Libs/SharedLibraryIxes.py
  test/NodeOps.py
  test/Parallel/multiple-parents.py
  test/Program.py
  test/Repository/Java.py
  test/Repository/JavaH.py
  test/Repository/Program.py
  test/Repository/RMIC.py
  test/Repository/StaticLibrary.py
  test/Repository/VariantDir.py
  test/Repository/include.py
  test/Repository/variants.py
  test/TAR/TAR.py
  test/TARGETS.py
  test/Value.py
  test/Variables/ListVariable.py
  test/Variables/PathVariable.py
  test/Variables/Variables.py
  test/VariantDir/VariantDir.py
  test/builderrors.py
  test/option/option--Y.py
  test/option/option-n.py
  test/option/stack-size.py
  testing/framework/TestSCons.py
Labels: testsuite

#4267 Remove an extra check in one ninja test
  CHANGES.txt
  test/ninja/build_libraries.py
Labels: testsuite

#4271 Fix one test in TestCommonTests
  testing/framework/TestCommonTests.py
Labels: testsuite

#4272 Use f-strings in framework and framework tests
  .github/workflows/framework_tests.yml
  testing/framework/TestCmd.py
  testing/framework/TestCmdTests.py
  testing/framework/TestCommon.py
  testing/framework/TestCommonTests.py
  testing/framework/TestSCons.py
  testing/framework/TestSConsMSVS.py
  testing/framework/TestSCons_time.py
Labels: testsuite

#4273 Fix interpreter usage in another FW test [skip appveyor]
  CHANGES.txt
  testing/framework/TestCmdTests.py
Labels: testsuite
