Repository SCons/scons, pull requests merged in 2022-05, with the labels that each got.

#4142 Use the logging framework for internal MSCommon debug output written to stdout
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/MSCommon/common.py
Labels: MSVC

#4131 MSVC modifications to version detection and batch file determination
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/MSCommon/vc.py
  SCons/Tool/MSCommon/vcTests.py
Labels: MSVC

#4143 docs: update parseconfig, parseflags, mergeflags
  CHANGES.txt
  SCons/Environment.py
  SCons/Environment.xml
  SCons/EnvironmentTests.py
  SCons/Tool/docbook/__init__.py
  doc/user/mergeflags.xml
  doc/user/parseconfig.xml
  doc/user/parseflags.xml
Labels: Documentation

#4141 [Ninja] fix mingw parse format
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/clang.py
  SCons/Tool/clangxx.py
  SCons/Tool/gcc.py
  SCons/Tool/gxx.py
  SCons/Tool/msvc.py
  SCons/Tool/ninja/NinjaState.py
  SCons/Tool/ninja/__init__.py
  SCons/Tool/ninja/ninja.xml
  test/ninja/mingw_depfile_format.py
  test/ninja/ninja_test_sconscripts/sconstruct_mingw_depfile_format
Labels: Ninja

#4137 [Ninja] added workarounds for ninja with python36 on windows
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/ninja/ninja_run_daemon.py
  SCons/Tool/ninja/ninja_scons_daemon.py
Labels: Ninja

#4136 [Ninja] added alias for ninja to know about generated files
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/ninja/NinjaState.py
  SCons/Tool/ninja/__init__.py
  SCons/Tool/ninja/ninja.xml
  test/ninja/generated_sources_alias.py
  test/ninja/ninja-fixture/gen_source.c
  test/ninja/ninja_test_sconscripts/sconstruct_generated_sources_alias
Labels: Ninja

#4133 [Ninja] Update ninja file generation to only create response files for build commands which exceed MAXLINELENGTH
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/ninja/Methods.py
  SCons/Tool/ninja/NinjaState.py
  test/ninja/ninja_test_sconscripts/sconstruct_response_file
  test/ninja/response_file.py
Labels: Ninja

#4121 Fix content-timestamp decider for symlinks
  CHANGES.txt
  RELEASE.txt
  SCons/Node/FS.py
  SCons/Node/FSTests.py
  test/Decider/content-timestamp-symlink.py
  testing/framework/TestSCons.py
Labels: decider

#4145 Remove last reference to distutils
  site_scons/Utilities.py
Labels: Release

#4117 MSVC changes for Visual Studio versions 6.0 to 7.1
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/MSCommon/common.py
  SCons/Tool/MSCommon/vc.py
  SCons/Tool/MSCommon/vs.py
Labels: MSVC

#4125 MSVC enhancement to bypassing Visual Studio autodetection
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/MSCommon/vc.py
  SCons/Tool/msvc.xml
  test/MSVC/MSVC_USE_SETTINGS.py
Labels: MSVC

#4111 Tweak the MSVC environment vars cache
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/MSCommon/common.py
  SCons/Tool/MSCommon/vc.py
  doc/man/scons.xml
Labels: MSVC

#4151 Fill in more SCONS_CACHE_MSVC_CONFIG detail [ci skip]
  RELEASE.txt
Labels: Release

#3761 Minor java improvements
  CHANGES.txt
  RELEASE.txt
  SCons/Scanner/Java.py
  SCons/Scanner/JavaTests.py
  SCons/Tool/__init__.py
  SCons/Tool/javac.py
  SCons/Tool/javac.xml
  SCons/Tool/javacTests.py
Labels: Java

#4157 Tweak the swig tool documentation
  SCons/Tool/swig.xml
  doc/scons.mod
Labels: Documentation

#4150 Improve variantdir docs
  SCons/Environment.xml
  SCons/Script/SConscript.xml
Labels: Documentation, variantdir

#4163 Fix some Py 3.11 depr warns in tests
  CHANGES.txt
  SCons/Scanner/ScannerTests.py
  SCons/Tool/ToolTests.py
  SCons/Tool/msvsTests.py
  SCons/cppTests.py
  testing/framework/TestCmdTests.py
  testing/framework/TestCommonTests.py
Labels: testsuite
