Repository SCons/scons, pull requests merged in 2023-10, with the labels that each got.

#4425 Further mod on msvc config cache locking
  SCons/Tool/MSCommon/common.py
Labels: maintenance

#4431 Microsoft tools: change relative imports to top-level absolute imports
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/midl.py
  SCons/Tool/mslib.py
  SCons/Tool/mslink.py
  SCons/Tool/mssdk.py
  SCons/Tool/msvc.py
  SCons/Tool/msvs.py
Labels: MSVC

#4430 Update assembly code in one test
  CHANGES.txt
  test/AS/as-live.py
Labels: testsuite

#4428 Fixup one test framework test
  testing/framework/TestCmdTests.py
Labels: testsuite

#4423 Fix issues in new scons_subproc_run
  SCons/Action.py
  SCons/ActionTests.py
Labels: maintenance

#4433 MSCommon: add custom formatter for debug log records
  SCons/Tool/MSCommon/common.py
Labels: MSVC

#4436 Add support for Java 21
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/JavaCommon.py
Labels: Java

#4432 MSVC: adjust the compiler search and warning message when configuring the environment.
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/MSCommon/vc.py
  test/MSVC/MSVC_USE_SETTINGS.py
Labels: MSVC
