Repository SCons/scons, pull requests merged in 2023-09, with the labels that each got.

#4405 Further tweak Alias() manpage entry
  SCons/Environment.xml
Labels: documentation

#4402 Handle json decode error in msvc cache
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/MSCommon/common.py
Labels: MSVC

#4406 [WIP] Added logic to properly initilize SCons to use gfortran if tool gfort…
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/gfortran.py
  test/Fortran/F03.py
  test/Fortran/fixture/SConstruct_gfortran_shared
  test/Fortran/fixture/gfortran_shared.f
  test/Fortran/gfortran.py
Labels: Fortran

#4407 msvc config cache: add locking on cachefile
  CHANGES.txt
  SCons/Tool/MSCommon/common.py
  SCons/Util/__init__.py
  SCons/Util/filelock.py
  test/ParseDepends.py
Labels: MSVC

#4300 Implement a new subprocess wrapper
  CHANGES.txt
  SCons/Action.py
  SCons/ActionTests.py
  SCons/Environment.py
  SCons/EnvironmentTests.py
  SCons/Platform/aix.py
  SCons/Tool/MSCommon/common.py
  SCons/Tool/clang.py
  SCons/Tool/clangxx.py
  SCons/Tool/docbook/__init__.py
  SCons/Tool/gcc.py
  SCons/Tool/swig.py
  SCons/Tool/xgettext.py
  test/fixture/mygcc.py
Labels: maintenance

#4413 Add header file for "hello world" example
  doc/user/build-install.xml
  doc/user/simple.xml
Labels: documentation

#4416 Niggly User Guide Chap 2/3 updates [skip appveyor]
  CHANGES.txt
  RELEASE.txt
  doc/user/less-simple.xml
  doc/user/simple.xml
Labels: documentation

#4421 TeX tests: skip if no makeindex
  CHANGES.txt
  RELEASE.txt
  test/DVIPDF/makeindex.py
  test/DVIPS/DVIPS.py
  test/TEX/LATEX.py
  test/TEX/LATEX2.py
  test/TEX/LATEXFLAGS.py
  test/TEX/TEX.py
  test/TEX/TEXFLAGS.py
  test/TEX/bibliography.py
  test/TEX/glossaries.py
  test/TEX/multi-run.py
  test/TEX/multiple_include.py
  test/TEX/multiple_include_subdir.py
  test/TEX/newglossary.py
  test/TEX/subdir_variantdir_include.py
  test/TEX/subdir_variantdir_include2.py
  test/TEX/subdir_variantdir_input.py
  test/TEX/variant_dir.py
  test/TEX/variant_dir_newglossary.py
Labels: testsuite

#4420 Bump dependency versions
  bin/docs-create-example-outputs.py
  bin/docs-update-generated.py
  bin/docs-validate.py
  doc/generated/variables.mod
  requirements-dev.txt
  requirements-pkg.txt
Labels: Release

#4419 MSVC: Fix unhandled MissingConfiguration exception.
  CHANGES.txt
  SCons/Tool/MSCommon/vc.py
Labels: bug, MSVC

#4418 Tweak Util module
  CHANGES.txt
  RELEASE.txt
  SCons/Errors.py
  SCons/Node/FS.py
  SCons/Util/UtilTests.py
  SCons/Util/__init__.py
  SCons/Util/envs.py
  SCons/Util/filelock.py
  SCons/Util/hashes.py
  SCons/Util/sctypes.py
  SCons/Util/stats.py
  doc/sphinx/SCons.Util.rst
  doc/sphinx/SCons.rst
  doc/sphinx/index.rst
Labels: maintenance

#4417 Updates for Export/Import doc
  CHANGES.txt
  RELEASE.txt
  SCons/Script/SConscript.xml
Labels: documentation

#4422 scons_subproc doc: remove keyword roles
  SCons/Action.py
Labels: documentation
