Repository SCons/scons, pull requests merged in 2023-06, with the labels that each got.

#4365 Maint: turn ActionBase into abstract class
  CHANGES.txt
  RELEASE.txt
  SCons/Action.py
Labels: maintenance

#4366 Minor scanner tweaks
  CHANGES.txt
  SCons/Scanner/D.py
  SCons/Scanner/JavaTests.py
  SCons/Scanner/LaTeX.py
  SCons/Scanner/__init__.py
Labels: maintenance

#4367 Follow on to PR #4348: more bool fixes
  CHANGES.txt
  RELEASE.txt
  SCons/ActionTests.py
  SCons/Builder.py
  SCons/BuilderTests.py
  SCons/CacheDir.py
  SCons/Debug.py
  SCons/Defaults.py
  SCons/Environment.py
  SCons/ExecutorTests.py
  SCons/Node/Alias.py
  SCons/Node/FS.py
  SCons/Node/NodeTests.py
  SCons/Node/Python.py
  SCons/Node/__init__.py
  SCons/SConf.py
  SCons/SConfTests.py
  SCons/Scanner/JavaTests.py
  SCons/Scanner/ProgTests.py
  SCons/Scanner/ScannerTests.py
  SCons/Subst.py
  SCons/SubstTests.py
  SCons/Taskmaster/TaskmasterTests.py
  SCons/Tool/DCommon.py
  SCons/Tool/JavaCommon.py
  SCons/Tool/MSCommon/MSVC/Util.py
  SCons/Tool/MSCommon/common.py
  SCons/Tool/cxx.py
  SCons/Tool/cyglink.py
  SCons/Tool/default.py
  SCons/Tool/docbook/__init__.py
  SCons/Tool/dvi.py
  SCons/Tool/filesystem.py
  SCons/Tool/install.py
  SCons/Tool/javac.py
  SCons/Tool/linkCommon/__init__.py
  SCons/Tool/msvsTests.py
  SCons/Tool/ninja/Utils.py
  SCons/Tool/packaging/__init__.py
  SCons/Tool/packaging/msi.py
  SCons/Tool/packaging/rpm.py
  SCons/Tool/pdf.py
  SCons/Tool/rmic.py
  SCons/Tool/textfile.py
  SCons/UtilTests.py
  SCons/cppTests.py
Labels: maintenance

#4368 maintenance: update/cleanup dblite module
  CHANGES.txt
  RELEASE.txt
  SCons/SConsign.py
  SCons/dblite.py
Labels: maintenance

#4353 Add support for D interface files
  CHANGES.txt
  RELEASE.txt
  SCons/Defaults.py
  SCons/Scanner/D.py
  SCons/Tool/DCommon.py
  SCons/Tool/DCommon.xml
  SCons/Tool/default.xml
  SCons/Tool/dmd.py
  SCons/Tool/gdc.py
  SCons/Tool/ldc.py
  test/D/di/Common/common.py
  test/D/di/Image/SConstruct_template
  test/D/di/Image/helloWorldMain.d
  test/D/di/Image/source/helloWorld.d
  test/D/di/sconstest-dmd.py
  test/D/di/sconstest-gdc.py
  test/D/di/sconstest-ldc.py
Labels: Tools, D language

#4369 Bytecode tweak for Py 3.12.0b3
  SCons/ActionTests.py
Labels: maintenance

#4370 Clean up Fortran tool generics
  CHANGES.txt
  SCons/Tool/FortranCommon.py
Labels: Fortran
