Repository SCons/scons, pull requests merged in 2023-08, with the labels that each got.

#4397 Correct warning type name
  doc/man/scons.xml
Labels: documentation

#4395 MINGW: Add missing directories to searched paths for mingw installs
  CHANGES.txt
  RELEASE.txt
  SCons/Platform/mingw.py
Labels: mingw

#4391 Change the default to error on missing SConscript
  CHANGES.txt
  README.rst
  RELEASE.txt
  SCons/Script/SConscript.py
  SCons/Script/SConscript.xml
  SCons/Script/__init__.py
  SCons/Warnings.py
  doc/man/scons.xml
  test/Removed/Old/SConscript-must_exist_deprecation.py
  test/Removed/Old/warn-missing-sconscript.py
  test/SConscript/must_exist.py
  test/option/option-f.py
Labels: maintenance

#4388 Add ability to save "local" help only
  CHANGES.txt
  RELEASE.txt
  SCons/Script/Main.py
  SCons/Script/SConsOptions.py
  SCons/Script/SConscript.py
  SCons/Script/SConscript.xml
  SCons/Script/__init__.py
  doc/user/output.xml
  test/Help.py
Labels: enhancement, documentation

#4403 Tweak a few tests "for form"
  CHANGES.txt
  test/File/File-relpath.py
  test/Java/DerivedSourceTest.py
  test/MSVC/MSVC_BATCH-spaces-targetdir.py
  test/MSVC/MSVC_NOTFOUND_POLICY.py
  test/MSVC/MSVC_SCRIPTERROR_POLICY.py
  test/MSVC/MSVC_SDK_VERSION.py
  test/MSVC/MSVC_SPECTRE_LIBS.py
  test/MSVC/MSVC_TOOLSET_VERSION.py
  test/MSVC/MSVC_USE_SCRIPT.py
  test/MSVC/MSVC_USE_SCRIPT_ARGS-fixture/SConstruct
  test/MSVC/MSVC_USE_SCRIPT_ARGS-fixture/fake_script.bat
  test/MSVC/MSVC_USE_SCRIPT_ARGS.py
  test/MSVC/MSVC_USE_SETTINGS.py
  test/MSVC/MSVC_UWP_APP.py
  test/MSVC/PCH-source.py
  test/MSVC/PCHCOM.py
  test/MSVC/PCHCOMSTR.py
  test/MSVC/PCHSTOP-errors.py
  test/MSVC/RCCOM.py
  test/MSVC/RCCOMSTR.py
  test/MSVC/TARGET_ARCH.py
  test/MSVC/VSWHERE-fixture/SConstruct
  test/MSVC/VSWHERE.py
  test/MSVC/batch-longlines.py
  test/MSVC/batch.py
  test/MSVC/embed-manifest.py
  test/MSVC/generate-rc.py
  test/MSVC/hierarchical.py
  test/MSVC/mssdk.py
  test/MSVC/msvc.py
  test/MSVC/msvc_badversion.py
  test/MSVC/msvc_cache_force_defaults.py
  test/MSVC/msvc_fixture/test.rc
  test/MSVC/multiple-pdb.py
  test/MSVC/no_msvc.py
  test/MSVC/pch-basics.py
  test/MSVC/pch-spaces-subdir.py
  test/MSVC/pdb-VariantDir-path.py
  test/MSVC/pdb-manifest.py
  test/MSVC/query_vcbat.py
Labels: maintenance, testsuite
