Repository SCons/scons, pull requests merged in 2023-07, with the labels that each got.

#4377 trivial update to textfile markup [skip appveyor]
  SCons/Tool/textfile.xml
Labels: documentation

#4375 Update project READMEs [skip ci]
  README-SF.rst
  README-local
  README-package.rst
Labels: documentation

#4371 Adjust help message about -H
  CHANGES.txt
  RELEASE.txt
  SCons/Script/Main.py
  test/Help.py
  test/SCONSFLAGS.py
  test/Variables/Variables.py
  test/Variables/help.py
Labels: documentation

#4050 build SCons packages with python tool 'build'
  .github/workflows/scons-package.yml
  ReleaseConfig
  SConstruct
  requirements-pkg.txt
  setup.cfg
Labels: CI / buildbot, Release

#4324 Fix 4312 and add Windows on ARM64 support for msvc.
  CHANGES.txt
  RELEASE.txt
  SCons/Platform/Platform.xml
  SCons/Platform/win32.py
  SCons/Tool/MSCommon/MSVC/SetupEnvDefault.py
  SCons/Tool/MSCommon/common.py
  SCons/Tool/MSCommon/vc.py
  SCons/Tool/MSCommon/vcTests.py
  SCons/Tool/MSCommon/vs.py
  doc/generated/variables.gen
  testing/framework/TestSConsMSVS.py
Labels: MSVC

#4381 Remove script path in PlatformTests
  CHANGES.txt
  SCons/Platform/PlatformTests.py
Labels: testsuite, Python 3.12

#4379 Cleanup the SCons build a bit
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/docbook/docbook.xml
  SCons/Tool/docbook/docs/SConstruct
  SCons/Tool/docbook/docs/html.xsl
  SCons/Tool/docbook/docs/manual.xml
  SCons/Tool/docbook/docs/pdf.xsl
  SCons/Tool/docbook/utils/xmldepend.xsl
  SConstruct
  bootstrap.py
  doc/SConscript
  site_scons/BuildCommandLine.py
  site_scons/SConsRevision.py
  site_scons/Utilities.py
  site_scons/epydoc.py
  site_scons/scons_local_package.py
  site_scons/site_init.py
  site_scons/soe_utils.py
  site_scons/update_build_info.py
  site_scons/zip_utils.py
Labels: Release

#4383 Incremental changes to runtest.py
  runtest.py
Labels: testsuite

#4382 Tweak CacheDir docs
  CHANGES.txt
  RELEASE.txt
  SCons/Environment.xml
  doc/user/caching.xml
Labels: documentation

#4378 Update test framework docs
  CHANGES.txt
  testing/framework/test-framework.rst
Labels: documentation

#4385 Docs tweaking: DefaultEnvironment and version strings
  SCons/Defaults.py
  SCons/Defaults.xml
  SCons/Tool/packaging/packaging.xml
  SCons/Tool/textfile.xml
  doc/man/scons.xml
Labels: documentation
