Repository SCons/scons, pull requests merged in 2024-10, with the labels that each got.

#4598 Fix short-option processing
  CHANGES.txt
  RELEASE.txt
  SCons/Script/SConsOptions.py
  test/AddOption/basic.py
  test/SCONSFLAGS.py
Labels: args_and_options

#4607 Fix nasm test
  CHANGES.txt
  RELEASE.txt
  test/AS/nasm.py
Labels: testsuite

#4611 Resolve 4605: enhance SCONS_MSCOMMON_DEBUG handling of invalid input
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/MSCommon/common.py
Labels: MSVC

#4618 Minor test cleanup - EnvironmentTests
  CHANGES.txt
  SCons/EnvironmentTests.py
Labels: testsuite

#4621 Add Beamer Theme Support for LaTeX Scanner
  CHANGES.txt
  RELEASE.txt
  SCons/Scanner/LaTeX.py
  SCons/Scanner/LaTeXTests.py
Labels: LaTex

#4622 Improve Repository docs
  CHANGES.txt
  RELEASE.txt
  SCons/Environment.py
  SCons/Environment.xml
  SCons/EnvironmentTests.py
  doc/man/scons.xml
  doc/user/repositories.xml
Labels: documentation

#4614 Adjust tests in case running as root
  CHANGES.txt
  RELEASE.txt
  SCons/CacheDirTests.py
  SCons/Node/FSTests.py
  SCons/Variables/PathVariableTests.py
  template/RELEASE.txt
  test/Install/Install.py
  test/VariantDir/errors.py
  testing/framework/TestCmd.py
Labels: testsuite

#4617 Add a tag to the cachedir
  CHANGES.txt
  RELEASE.txt
  SCons/CacheDir.py
  SCons/CacheDirTests.py
  test/CacheDir/CacheDir.py
  test/CacheDir/CacheDir_TryCompile.py
  test/CacheDir/NoCache.py
  test/CacheDir/SideEffect.py
  test/CacheDir/VariantDir.py
  test/CacheDir/debug.py
  test/CacheDir/environment.py
  test/CacheDir/multi-targets.py
  test/CacheDir/multiple-targets.py
  test/CacheDir/option--cd.py
  test/CacheDir/option--cf.py
  test/CacheDir/option--cr.py
  test/CacheDir/option--cs.py
  test/CacheDir/scanner-target.py
  test/CacheDir/source-scanner.py
  test/CacheDir/up-to-date-q.py
  test/CacheDir/value_dependencies.py
Labels: cachedir
