Repository SCons/scons, pull requests merged in 2024-11, with the labels that each got.

#4610 MSVS test fixes and minor changes to msvs tool
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/msvs.py
  SCons/Tool/msvs.xml
  SCons/Tool/msvsTests.py
  test/MSVS/common-prefix.py
  test/MSVS/runfile.py
  test/MSVS/vs-6.0-clean.py
  test/MSVS/vs-7.0-clean.py
  test/MSVS/vs-7.0-files.py
  test/MSVS/vs-7.0-scc-files.py
  test/MSVS/vs-7.0-scc-legacy-files.py
  test/MSVS/vs-7.0-variant_dir.py
  test/MSVS/vs-7.1-clean.py
  test/MSVS/vs-7.1-files.py
  test/MSVS/vs-7.1-scc-files.py
  test/MSVS/vs-7.1-scc-legacy-files.py
  test/MSVS/vs-7.1-variant_dir.py
  test/MSVS/vs-files.py
  test/MSVS/vs-mult-auto-guid.py
  test/MSVS/vs-mult-auto-vardir-guid.py
  test/MSVS/vs-mult-auto-vardir.py
  test/MSVS/vs-mult-auto.py
  test/MSVS/vs-mult-noauto-vardir.py
  test/MSVS/vs-mult-noauto.py
  test/MSVS/vs-scc-files.py
  test/MSVS/vs-scc-legacy-files.py
  test/MSVS/vs-variant_dir.py
  testing/framework/TestSConsMSVS.py
Labels: MSVC

#4633 Add as_dict flag to env.Dictionary
  CHANGES.txt
  RELEASE.txt
  SCons/Environment.py
  SCons/Environment.xml
  SCons/EnvironmentTests.py
Labels: Environment

#4643 Integrate `from __future__ import annotations`
  CHANGES.txt
  RELEASE.txt
  SCons/Action.py
  SCons/ActionTests.py
  SCons/Builder.py
  SCons/BuilderTests.py
  SCons/Defaults.py
  SCons/Environment.py
  SCons/Errors.py
  SCons/Executor.py
  SCons/Node/FS.py
  SCons/Node/FSTests.py
  SCons/Node/NodeTests.py
  SCons/Node/__init__.py
  SCons/SConf.py
  SCons/Script/Main.py
  SCons/Script/SConsOptions.py
  SCons/Script/SConscript.py
  SCons/Subst.py
  SCons/Tool/FortranCommon.py
  SCons/Tool/JavaCommon.py
  SCons/Tool/__init__.py
  SCons/Tool/jar.py
  SCons/Tool/lex.py
  SCons/Tool/ninja/Methods.py
  SCons/Tool/ninja/Utils.py
  SCons/Tool/yacc.py
  SCons/Util/UtilTests.py
  SCons/Util/__init__.py
  SCons/Util/envs.py
  SCons/Util/filelock.py
  SCons/Util/hashes.py
  SCons/Util/sctypes.py
  SCons/Util/sctyping.py
  SCons/Variables/BoolVariable.py
  SCons/Variables/EnumVariable.py
  SCons/Variables/ListVariable.py
  SCons/Variables/PackageVariable.py
  SCons/Variables/PathVariable.py
  SCons/Variables/__init__.py
  SCons/Warnings.py
  pyproject.toml
  runtest.py
  test/Variables/PackageVariable.py
  testing/framework/TestCmd.py
  testing/framework/TestCommon.py
  testing/framework/TestSCons.py
Labels: maintenance

#4634 User Guide: Add mention of `no_progress` option when user passes -Q
  doc/user/command-line.xml
Labels: documentation

#4642 Remove Python 3.6 support
  CHANGES.txt
  RELEASE.txt
  ReleaseConfig
  SCons/Action.py
  SCons/ActionTests.py
  SCons/Script/Main.py
  doc/man/scons.xml
  pyproject.toml
  runtest.py
  scripts/scons-configure-cache.py
  scripts/scons.py
  scripts/sconsign.py
  testing/framework/TestSCons.py
Labels: maintenance, Release

#4648 Tweak Clean and NoClean manpage entries
  CHANGES.txt
  RELEASE.txt
  SCons/Environment.py
  SCons/Environment.xml
  doc/generated/functions.gen
Labels: documentation

#4653 Unknown variables from Variables file are now reported
  CHANGES.txt
  RELEASE.txt
  SCons/Variables/VariablesTests.py
  SCons/Variables/__init__.py
Labels: Variables

#4650 Add type hints to main Node script
  CHANGES.txt
  RELEASE.txt
  SCons/Node/NodeTests.py
  SCons/Node/__init__.py
Labels: maintenance
