Repository SCons/scons, pull requests merged in 2024-07, with the labels that each got.

#4534 MSVC: detection fixes
  CHANGES.txt
  RELEASE.txt
  SCons/Tool/MSCommon/MSVC/Config.py
  SCons/Tool/MSCommon/MSVC/Kind.py
  SCons/Tool/MSCommon/MSVC/Policy.py
  SCons/Tool/MSCommon/MSVC/Registry.py
  SCons/Tool/MSCommon/MSVC/ScriptArguments.py
  SCons/Tool/MSCommon/MSVC/ScriptArgumentsTests.py
  SCons/Tool/MSCommon/MSVC/Util.py
  SCons/Tool/MSCommon/MSVC/__init__.py
  SCons/Tool/MSCommon/README.rst
  SCons/Tool/MSCommon/__init__.py
  SCons/Tool/MSCommon/sdk.py
  SCons/Tool/MSCommon/vc.py
  SCons/Tool/MSCommon/vcTests.py
  SCons/Tool/MSCommon/vs.py
  SCons/Tool/msvc.py
  SCons/Tool/msvc.xml
  SCons/Tool/msvsTests.py
  test/MSVC/MSVC_SDK_VERSION.py
  test/MSVC/MSVC_TOOLSET_VERSION.py
  test/MSVC/MSVC_UWP_APP.py
  test/MSVC/VSWHERE-fixture/SConstruct
  test/MSVC/VSWHERE.py
  test/MSVC/msvc.py
  test/MSVC/msvc_cache_force_defaults.py
  test/MSVC/no_msvc.py
  test/MSVC/query_vcbat.py
  test/fixture/no_msvc/no_msvcs_sconstruct.py
  test/fixture/no_msvc/no_msvcs_sconstruct_msvc_query_toolset_version.py
  test/fixture/no_msvc/no_msvcs_sconstruct_msvc_sdk_versions.py
  test/fixture/no_msvc/no_msvcs_sconstruct_msvc_toolset_versions.py
  test/fixture/no_msvc/no_msvcs_sconstruct_tools.py
  test/fixture/no_msvc/no_msvcs_sconstruct_version.py
  testing/framework/TestSConsMSVS.py
Labels: MSVC

#4566 Update manpage intro
  CHANGES.txt
  RELEASE.txt
  doc/man/scons.xml
Labels: documentation

#4564 Update $VSWHERE description
  SCons/Tool/msvc.xml
  doc/generated/builders.gen
  doc/generated/functions.gen
  doc/generated/tools.gen
  doc/generated/variables.gen
  windows_ci_skip.txt
Labels: documentation

#4568 Some minor test tweaking
  CHANGES.txt
  bin/scons-time.py
  test/CacheDir/value_dependencies/SConstruct
  test/Configure/custom-tests.py
  test/Errors/preparation.py
  test/GetBuildFailures/option-k.py
  test/Java/JARCHDIR.py
  test/Java/JARFLAGS.py
  test/Java/JAVACFLAGS.py
  test/Java/JAVACLASSPATH.py
  test/Java/JAVAH.py
  test/Java/multi-step.py
  test/Java/no-JARCHDIR.py
  test/Java/swig-dependencies.py
  test/LEX/no_lex.py
  test/MSVC/MSVC_USE_SCRIPT.py
  test/MSVC/MSVC_USE_SETTINGS.py
  test/MSVC/PCH-source.py
  test/MSVC/TARGET_ARCH.py
  test/MSVC/batch-longlines.py
  test/MinGW/MinGWSharedLibrary.py
  test/MinGW/WINDOWS_INSERT_DEF.py
  test/Removed/Old/warn-missing-sconscript.py
  test/TEX/LATEX2.py
  test/TEX/LATEXCOMSTR.py
  test/TEX/PDFLATEXCOMSTR.py
  test/TEX/PDFTEXCOMSTR.py
  test/TEX/TEXCOMSTR.py
  test/TEX/configure.py
  test/TEX/dryrun.py
  test/TEX/rename_result.py
  test/TEX/usepackage.py
  test/Variables/import.py
  test/YACC/live-check-output-cleaned.py
  test/ZIP/ZIP.py
  test/ZIP/ZIPROOT.py
  test/ZIP/ZIP_OVERRIDE_TIMESTAMP.py
  test/gettext/POTUpdate/UserExamples.py
  test/implicit-cache/DualTargets.py
  test/no-global-dependencies.py
  test/sconsign/script/SConsignFile.py
  testing/framework/TestCommonTests.py
  testing/framework/TestSCons.py
Labels: testsuite

#4570 Bump SCons "added" version to 4.8
  SCons/Script/Main.py
  SCons/Script/SConscript.xml
  doc/man/scons.xml
Labels: documentation

#4575 Add timeout to test/ninja/default_targets.py
  CHANGES.txt
  test/ninja/default_targets.py
  test/ninja/ninja_test_sconscripts/sconstruct_default_targets
Labels: testsuite

#4578 Switch scons build to use setuptools version hook
  CHANGES.txt
  pyproject.toml
  setup.py
Labels: Release

#4576 Restore usage of "from SCons.Variables import *`
  CHANGES.txt
  RELEASE.txt
  SCons/Variables/VariablesTests.py
  SCons/Variables/__init__.py
Labels: Variables
