Repository SCons/scons, pull requests merged in 2024-03, with the labels that each got.

#4483 Update MSVC_VERSION usage and table
  CHANGES.txt
  SCons/Platform/Platform.xml
  SCons/Tool/mslink.xml
  SCons/Tool/msvc.xml
  SCons/Tool/msvs.xml
  doc/generated/builders.gen
  doc/generated/examples/caching_ex-random_1.xml
  doc/generated/examples/troubleshoot_explain1_3.xml
  doc/generated/examples/troubleshoot_stacktrace_2.xml
  doc/generated/examples/troubleshoot_taskmastertrace_1.xml
  doc/generated/functions.gen
  doc/generated/tools.gen
  doc/generated/variables.gen
  doc/man/scons.xml
  doc/scons.mod
  doc/user/builders-built-in.xml
  doc/user/sideeffect.xml
  doc/user/simple.xml
  doc/user/troubleshoot.xml
Labels: documentation

#4488 Cleanup Warnings module
  CHANGES.txt
  RELEASE.txt
  SCons/Script/SConsOptions.py
  SCons/Warnings.py
  SCons/WarningsTests.py
  doc/man/scons.xml
  doc/sphinx/SCons.rst
  doc/sphinx/index.rst
Labels: documentation, maintenance

#4487 Assorted manpage updates
  CHANGES.txt
  RELEASE.txt
  SCons/Defaults.xml
  SCons/Environment.py
  SCons/Environment.xml
  doc/man/scons.xml
  doc/user/builders-built-in.xml
Labels: documentation

#4490 Lock creation of CacheDir config
  CHANGES.txt
  RELEASE.txt
  SCons/CacheDir.py
  SCons/Tool/MSCommon/common.py
  SCons/Util/filelock.py
Labels: cachedir

#4492 Tweak documentation build
  doc/SConscript
Labels: documentation, Release

#4494 Update MergeFlags doc
  CHANGES.txt
  RELEASE.txt
  SCons/Environment.xml
Labels: documentation

#4496 Give more control to docs build
  CHANGES.txt
  RELEASE.txt
  doc/SConscript
  site_scons/BuildCommandLine.py
Labels: documentation, Release

#4491 Updates on Value nodes
  .appveyor.yml
  CHANGES.txt
  RELEASE.txt
  SCons/Environment.xml
  SCons/Node/PythonTests.py
  SCons/Taskmaster/Job.py
  test/Actions/function.py
  test/Value/GetContent.py
  test/Value/Value.py
Labels: documentation, testsuite

#4505 Fix isabs() check in NodeInfo for Py 3.13
  CHANGES.txt
  RELEASE.txt
  SCons/Node/FS.py
  SCons/Node/__init__.py
Labels: python 3.13

#4485 Fix #3935 OSErrors being hidden
  CHANGES.txt
  RELEASE.txt
  SCons/Action.py
  SCons/CacheDirTests.py
  SCons/Defaults.py
  SCons/Node/FS.py
  SCons/Node/__init__.py
  SCons/SConfTests.py
  SCons/Taskmaster/TaskmasterTests.py
  SCons/Variables/PathVariable.py
Labels: cachedir

#4507 Remove redundant node-info code
  CHANGES.txt
  RELEASE.txt
  SCons/Node/Alias.py
  SCons/Node/FS.py
  SCons/Node/Python.py
Labels: maintenance
