Repository SCons/scons, pull requests merged in 2025-07, with the labels that each got.

#4739 Update Configure docs, again
  CHANGES.txt
  RELEASE.txt
  SCons/Node/__init__.py
  doc/man/scons.xml
Labels: documentation

#4735 Update testing intro doc
  testing/framework/test-framework.rst
Labels: testsuite

#4741 Testing: Update the packaging tar bz2 and xz tests on windows
  CHANGES.txt
  RELEASE.txt
  test/packaging/tar/bz2_packaging.py
  test/packaging/tar/gz.py
  test/packaging/tar/xz_packaging.py
  testing/ci/windows_ci_skip.txt
  testing/framework/TestSConsTar.py
Labels: Op Sys: Windows, testsuite

#4742 Update AppendUnique, PrependUnique unit tests
  CHANGES.txt
  SCons/EnvironmentTests.py
Labels: testsuite
