Repository SCons/scons, pull requests merged in 2025-02, with the labels that each got.

#4677 Handle --debug containing memoizer
  CHANGES.txt
  RELEASE.txt
  SCons/Script/__init__.py
  test/option/debug-memoizer.py
Labels: args_and_options

#4676 :bug: Allow passing `extra_libs` to `CheckLibWithHeader`
  CHANGES.txt
  RELEASE.txt
  SCons/SConf.py
  doc/man/scons.xml
  test/Configure/CheckLibWithHeader_extra_libs.py
  test/Configure/fixture/checklib_extra/SConstruct
  test/Configure/fixture/checklib_extra/conftest.skip
  test/Configure/fixture/checklib_extra/libA/SConstruct
  test/Configure/fixture/checklib_extra/libA/libA.c
  test/Configure/fixture/checklib_extra/libA/libA.h
  test/Configure/fixture/checklib_extra/libB/SConstruct
  test/Configure/fixture/checklib_extra/libB/libB.c
  test/Configure/fixture/checklib_extra/libB/libB.h
  test/Configure/fixture/checklib_extra/src/test.c
Labels: Configure

#4675 Some tweaks to project description docs
  CONTRIBUTING.rst
  doc/overview.rst
Labels: documentation

#4680 Fix small problem in a yacc test
  CHANGES.txt
  test/YACC/live.py
Labels: testsuite

#4681 Update doc development overview
  doc/images/overview.graphml
  doc/images/overview.png
  doc/overview.rst
Labels: documentation

#4689 Framework: fixture methods now handle lists for dstdir
  CHANGES.txt
  testing/framework/TestCmd.py
Labels: testsuite
