Repository SCons/scons, pull requests merged in 2025-03, with the labels that each got.

#4692 Fix typos in CCFLAGS test
  CHANGES.txt
  test/CC/CCFLAGS.py
Labels: testsuite

#4695 Fix CacheDir initialization so works on 3.7 also
  .appveyor.yml
  CHANGES.txt
  RELEASE.txt
  SCons/CacheDir.py
Labels: cachedir

#4685 Fix infinite hang in wait_for_process_to_die() on Windows
  CHANGES.txt
  RELEASE.txt
  SCons/Util/UtilTests.py
  SCons/Util/__init__.py
Labels: Ninja
